# Generated by Django 5.0.7 on 2024-08-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_column='full_name', max_length=100)),
                ('email', models.CharField(db_column='email', max_length=100, unique=True)),
            ],
        ),
    ]
